### PR TITLE
mylg.config now in .config. and many small non-code changes.

### PR DESCRIPTION
**Pull request by jungle-boogie**

### CODE REVIEW

**Comment by mehrdadrad** [comment]
@jungle-boogie  Thanks for the commits! 
- If we change the config per your change , the current users lose their configuration, let's postpone this for later.
- I can not see the binary file under github

**Comment by jungle-boogie** [comment]
@mehrdadrad,

yes, the config would be lost. How can we make it copy it to the new location? Alternatively, in release notes you can mention the new location.

The binary file was a mistake as I built and added mylg on my branch and inadvertently committed it.

**Comment by gummiboll** [comment]
A solution would be to run a check if ```~/.mylg.config``` exists, move it to ```~/.config/mylg.config``` just before the configuration is loaded.

However, and this is just my $0.02, I dont think mylg should create/use a generically named directory in the users ~ for just one file. I kinda feel like mylg's configuration file should be just a dotfile in ~. If mylg should create a directory to store its configuration I think it should use ```~/.mylg/config``` or smething like that.

**Comment by jungle-boogie** [comment]
The reason I like it in `.config` is because that's where lots of other configuration files are saved. In my own `.config`, I have: htop, hub, mutt, ntfy, profanity, syncthing.

If I want to automate backups of my home directory, I could do everything in my home directory or simply important things I want to keep, which includes `.config`. I think there's a stronger likelihood of someone forgetting `mylg` saves files to ~/.mylg.config and not ~/.config/mylg.config

You're right, some the items in my `.config` are directories that contain only single files within the directory.

```
% ls -l .config/ntfy
total 4
-rw-r--r--  1 user user  92 Apr 19  2016 ntfy.yml
```

**Comment by gummiboll** [comment]
Ah, I have missed the fact that many applications nowdays put their config in ```.config```. Then my point about that might be a bit useless. :D

**Comment by jungle-boogie** [comment]
no problem!

Would you be happy with `~/.config/mylg/mylg.config`?

If so, do you have any suggestions on check/move code?

**Comment by mehrdadrad** [comment]
@jungle-boogie I think we need to have an issue for this subject (change configuration path) then we can discuss and track it.

**Comment by mehrdadrad** [comment]
@jungle-boogie Thanks!

**Pull request merged**
